export const translator = {
  textIndexes: {
    en: {
      sbaqi: "Senstate Basic Air Quality Index (SBAQI)",
      caqi: "Common Air Quality Index (CAQI)",
      eaqi: "European Air Quality Index (EAQI)",
    },
    bg: {
      sbaqi: "Базов индекс за качеството на въздуха (SBAQI)",
      caqi: "Общ индекс за качество на въздуха (CAQI)",
      eaqi: "Европейски индекс за качеството на въздуха (EAQI)",
    },
  },
  CAQMDescriptions: {
    en: {
      1: "Enjoy all outdoor activities",
      2: "Enjoy your usual outdoor activities",
      3: "Unhealthy for sensitive groups",
      4: "Avoid strenuous outdoor activities",
      5: "Avoid all outdoor physical activities",
    },
    bg: {
      1: "Насладете се на всички дейности на открито",
      2: "Насладете се на обичайните си дейности на открито",
      3: "Нездравословно за чувствителни групи",
      4: "Избягвайте напрегнатите дейности на открито",
      5: "Избягвайте всякакви физически дейности на открито",
    },
  },
  textVarious: {
    en: {
      moreInformation: "For more information visit",
      lastCalculated: "Last calculated: ",
      pollution: " pollution",
      chartTitle: "Air Quality Index for the last 24 hours",
    },
    bg: {
      moreInformation: "За повече информация посетете ",
      lastCalculated: "Последно изчислен: ",
      pollution: " замърсяване",
      chartTitle: "Индекс на качеството на въздуха за последните 24 часа",
    },
  },
  textWidgets: {
    en: {
      weatherTitle: "Weather",
      particulatesTitle: "Particulates",
      gasesTitle: "Gases",
      pmDescription: "Particulate Matter, mg/m3",
      humidityTitle: "Humidity",
      temperatureTitle: "Temperature",
      pressureTitle: "Pressure",
      humidityDescription: "Relative Humidity",
      temperatureDescription: "Temperature",
      pressureDescription: "Pressure",
      no2Description: "Nitrogen Dioxide",
      so2Description: "Sulfur Dioxide",
      coDescription: "Carbon Monoxide",
      о3Description: "Ozone",
      limitHText: "Concentration limit for averaging period of 1 hour",
    },
    bg: {
      weatherTitle: "Метео",
      particulatesTitle: "Прахови частици",
      gasesTitle: "Газове",
      pmDescription: "Прахови частици, mg/m3",
      humidityTitle: "Влажност",
      temperatureTitle: "Температура",
      pressureTitle: "Налягане",
      humidityDescription: "Относителна влажност",
      temperatureDescription: "Температура",
      pressureDescription: "Атмосферно налягане",
      no2Description: "Азотен диоксид",
      so2Description: "Серен диоксид",
      coDescription: "Въглероден окис",
      о3Description: "Озон",
      limitHText: "Лимит на концентрация за период на усредняване от 1 час",
    },
  },
  statesText: {
    en: {
      veryLow: "Very low",
      low: "Low",
      medium: "Medium",
      high: "High",
      veryHigh: "Very high",
    },
    bg: {
      veryLow: "Много слабо",
      low: "Слабо",
      medium: "Средно",
      high: "Високо",
      veryHigh: "Много високо",
    },
  },
};
